import tkinter as tk

window = tk.Tk()
window.title("Mini Calculator")

button1 = tk.Button(text="1")
button1.grid(row=3, column= 0)
button2 = tk.Button(text="2")
button2.grid(row=3, column= 1)
button3 = tk.Button(text="3")
button3.grid(row=3, column= 2)
button4 = tk.Button(text="4")
button4.grid(row=2, column= 0)
button5 = tk.Button(text="5")
button5.grid(row=2, column= 1)
button6 = tk.Button(text="6")
button6.grid(row=2, column= 2)
button7 = tk.Button(text="7")
button7.grid(row=1, column= 0)
button8 = tk.Button(text="8")
button8.grid(row=1, column= 1)
button9 = tk.Button(text="9")
button9.grid(row=1, column= 2)
button0 = tk.Button(text="0")
button0.grid(row=4, column= 0)

buttonPlus = tk.Button(text="+")
buttonPlus.grid(row=4, column= 2)
buttonMinus = tk.Button(text="-")
buttonMinus.grid(row=3, column= 3)
buttonMal = tk.Button(text="×")
buttonMal.grid(row=2, column= 3)
buttonDurch = tk.Button(text="÷")
buttonDurch.grid(row=1, column= 3)
buttonGleich = tk.Button(text="=")
buttonGleich.grid(row=4, column= 3)
buttonKomma = tk.Button(text=".")
buttonKomma.grid(row=4, column= 1)

buttonClear = tk.Button(text="C")
buttonClear.grid(row=5, column= 3)

window.mainloop()