import tkinter as tk

window = tk.Tk()
window.title("Mini Calculator")

button1 = tk.Button(text="1")
button1.pack()
button2 = tk.Button(text="2")
button2.pack()
button3 = tk.Button(text="3")
button3.pack()
button4 = tk.Button(text="4")
button4.pack()
button5 = tk.Button(text="5")
button5.pack()
button6 = tk.Button(text="6")
button6.pack()
button7 = tk.Button(text="7")
button7.pack()
button8 = tk.Button(text="8")
button8.pack()
button9 = tk.Button(text="9")
button9.pack()
button0 = tk.Button(text="0")
button0.pack()

buttonPlus = tk.Button(text="+")
buttonPlus.pack()
buttonMinus = tk.Button(text="-")
buttonMinus.pack()
buttonMal = tk.Button(text="×")
buttonMal.pack()
buttonDurch = tk.Button(text="÷")
buttonDurch.pack()
buttonGleich = tk.Button(text="=")
buttonGleich.pack()
buttonKomma = tk.Button(text=".")
buttonKomma.pack()

window.mainloop()